import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./_components/theme-provider";

import Footer from "./_components/Footer";
import Navigation from "./_components/Navigation";
import { FoodCardContextProvider } from "./_contexts/FoodCardContext";

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
});
export const metadata: Metadata = {
  title: "Food delivery app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={manrope.variable}>
      <body className="min-h-full flex flex-col">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          scriptProps={{ "data-cfasync": "false" }}
          enableSystem
          disableTransitionOnChange
        >
          <FoodCardContextProvider>
            <main>
              <Navigation />
              {children}
              <Footer />
            </main>
          </FoodCardContextProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
